### ISSUE TITLE
New Energy Sensors for Pacex BMS

### ISSUE THREAD

**Issue by MBRetrofit** [bagges/deye-esp32-bridge#28]
Based on Power sensor

 ```  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "${bms_name} power"~~~

I renamed this Power sensor as RAW - as this can be positive or negative and I created 2 more for Charging Power and Discharging Power and another 2 ones for Charging Energy and Discharging Energy.

````
# 1. Charging Power (W) - Template Sensor
- platform: template
  id: charging_power  # Required for reference
  name: "${device1} Charging Power"
  unit_of_measurement: "W"
  device_class: power
  state_class: measurement
  lambda: |-
    float power = id(bms_power_raw).state;
    return (power > 0) ? power : 0.0f;

# 2. Discharging Power (W) - Template Sensor
- platform: template
  id: discharging_power  # Required for reference
  name: "${device1} Discharging Power"
  unit_of_measurement: "W"
  device_class: power
  state_class: measurement
  lambda: |-
    float power = id(bms_power_raw).state;
    return (power < 0) ? -power : 0.0f;

# Charging Energy (kWh)
- platform: integration
  name: "bms_charging_energy"
  sensor: charging_power          # Refers to the template sensor's ID
  time_unit: "h"                 # Required! Options: "s", "min", "h", "d"
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  accuracy_decimals: 3
  filters:
    - multiply: 0.001            # Converts W → kW (1 kWh = 1 kW * 1 h)

# Discharging Energy (kWh)
- platform: integration
  name: "bms_discharging_energy"
  sensor: discharging_power       # Refers to the template sensor's ID
  time_unit: "h"                  # Must match the unit above
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  accuracy_decimals: 3
  filters:
    - multiply: 0.001
````

Based on Charging/Discharging Energy a Utility Meter can be added on ````configuration.yaml```

````utility_meter:
  daily_charging_energy:
    source: sensor.bms_charging_energy
    cycle: daily
  daily_discharging_energy:
    source: sensor.bms_discharging_energy
    cycle: daily

````
