### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#4]
As far as I understand, the information is provided in a webbrowser when typing the IP address of the ESP32.
I want the data in my house automatisation FHEM. Is it possible to publish the information via MQTT? Or is there any other way to provide the information to my house automatisation?

**Comment by bagges** [comment]
For mqtt you have to provide mqtt config in the yaml. That should then work with fhem, iobroker,...

**Comment by Gisbert1** [comment]
Hi bagges,
for me it's more than difficult, at my level even impossible, to add MQTT to your code (I'm using credentials with my MQTT broker).
Could you help me with the implementation and an example? If it's then necessary to put the code multiple times at different lines in your code, I could do that.
Regards and Greetings from NRW to Saarland
Gisbert

**Comment by bagges** [comment]
You just have to add this one time to your yaml:

```
mqtt:
  broker: IP
  port: PORT
  topic_prefix: PREFIX (opt.)
  username: USER (opt.)
  password: PASSW (opt.)
```
